### ISSUE TITLE
Ask for supporting loadFromKeystore

### ISSUE THREAD

**Issue by erickorbit** [FireStack-Lab/LaksaJ#14]
Zilliqa supports 3 kind of import wallet.
- by privatekey
- by mnemonic phrase
- by keystore

Can you support load wallet from keystore?

**Comment by renlulu** [comment]
Hi, thank you for your feedback, but I do think we already have the function import from keystore aka file: 

` public static Account fromFile(String file, String passphrase) throws Exception {
        String privateKey = KeyTools.decryptPrivateKey(file, passphrase);
        return new Account(privateKey);
  }`

You can check for this. Which I have't implemented is by mnemonic phrase. I think I should do this :D

**Comment by erickorbit** [comment]
Thank you! It is that I want.
