### ISSUE TITLE
Add isValidChecksumAddress and toChecksumAddress utilities

### ISSUE THREAD

**Issue by evesnow91** [FireStack-Lab/LaksaJ#3]
### **Reference implementation**

**isValidChecksumAddress:** https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/9368fb34a0d443797adc1ecbcb9728db9ce75e97/packages/zilliqa-js-crypto/src/util.ts#L99

**toChecksumAddress:** https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/9368fb34a0d443797adc1ecbcb9728db9ce75e97/packages/zilliqa-js-crypto/src/util.ts#L69

**Comment by renlulu** [comment]
isValidChecksumAddress is already exists(In com.firestack.laksaj.utils.Validation), but I named it isAddress. 
I will add the second one.Thanks!

**Comment by renlulu** [comment]
Already done!
