### ISSUE TITLE
build instructions / jar

### ISSUE THREAD

**Issue by AndreiD** [FireStack-Lab/LaksaJ#6]
Hello,

can you write **some build instructions** and generate **a jar** from the files ?

I'm having a hard time building this because of small thinks like import com.sun.tools.javac.util.Assert;, setting up lombok etc.

Thanks

**Comment by renlulu** [comment]
Hi, you can try gradle build -x test

**Comment by AndreiD** [comment]
all good now. no need to build it since you added it in maven
